# Generated by Django 4.2 on 2023-04-21 00:45

import core.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0000_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorDataResultType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            managers=[
                ("types", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("domain", models.URLField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SiteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SitePageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_lab", core.fields.CubeField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="site",
            name="categories",
            field=models.ManyToManyField(to="core.sitecategory"),
        ),
        migrations.AddField(
            model_name="site",
            name="page_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.sitepagetype"
            ),
        ),
        migrations.CreateModel(
            name="ScrapeJobSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dominant_colors_visual", models.JSONField()),
                ("dominant_colors_web", models.JSONField()),
                ("dominant_colors_brand", models.JSONField()),
                (
                    "job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.scrapejob",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeJobConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scrape_interval_seconds", models.IntegerField()),
                ("scrape_max_retries", models.IntegerField()),
                ("scrape_retry_interval_seconds", models.IntegerField()),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scrapejob",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.site"
            ),
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("html", "Html"),
                            ("css", "Css"),
                            ("favicon", "Favicon"),
                            ("image", "Image"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_url", models.URLField()),
                ("object_checksum", models.CharField(max_length=100, unique=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColorDataResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_lab", core.fields.CubeField()),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.scrapejob"
                    ),
                ),
                (
                    "result_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.colordataresulttype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.site"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.datasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="sitecolor",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["color_lab"], name="core_siteco_color_l_18bf7b_gist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sitecolor",
            unique_together={("site", "color_lab")},
        ),
    ]
